import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '0.64.0:0',
  releaseNotes: {
    en_US: `Upgrades Navidrome to 0.64.0. **This release re-encodes every database ID to a new format — back up your library database (a full StartOS backup) before upgrading if you haven't already.** Adds a new artwork loading pipeline, natural sort order, playlist favorites, and much faster playlist imports on large libraries. Also fixes several security issues: SQL injection, an IDOR in share ownership, an SSRF bypass in the plugin HTTP/WebSocket clients, and a login rate-limit bypass. Upstream also adds an experimental Jellyfin Music API, but it's not exposed in this package yet — several clients can't sync against it in this release, and the fix isn't in a tagged Navidrome version yet.`,
    es_ES: `Actualiza Navidrome a la versión 0.64.0. **Esta versión recodifica todos los ID de la base de datos a un nuevo formato — haga una copia de seguridad de su base de datos (una copia de seguridad completa de StartOS) antes de actualizar si aún no lo ha hecho.** Añade una nueva canalización de carga de portadas, orden natural, favoritos de listas de reproducción y una importación de listas mucho más rápida en bibliotecas grandes. También corrige varios problemas de seguridad: inyección SQL, un IDOR en la propiedad de los recursos compartidos, un bypass de SSRF en los clientes HTTP/WebSocket de plugins y un bypass del límite de intentos de inicio de sesión. Upstream también añade una API experimental de Jellyfin Music, pero aún no está disponible en este paquete — varios clientes no pueden sincronizar con ella en esta versión, y la corrección todavía no está en una versión etiquetada de Navidrome.`,
    de_DE: `Aktualisiert Navidrome auf 0.64.0. **Diese Version kodiert alle Datenbank-IDs in ein neues Format um — sichern Sie Ihre Datenbank (ein vollständiges StartOS-Backup), falls noch nicht geschehen.** Fügt eine neue Artwork-Ladepipeline, natürliche Sortierung, Playlist-Favoriten und deutlich schnelleren Playlist-Import bei großen Bibliotheken hinzu. Behebt außerdem mehrere Sicherheitsprobleme: SQL-Injection, ein IDOR bei der Freigabe-Eigentümerschaft, einen SSRF-Bypass in den Plugin-HTTP/WebSocket-Clients sowie einen Bypass des Login-Rate-Limits. Upstream fügt außerdem eine experimentelle Jellyfin-Music-API hinzu, die in diesem Paket aber noch nicht verfügbar ist — mehrere Clients können in dieser Version nicht damit synchronisieren, und die Korrektur ist noch in keiner getaggten Navidrome-Version enthalten.`,
    pl_PL: `Aktualizuje Navidrome do wersji 0.64.0. **Ta wersja przekodowuje wszystkie identyfikatory bazy danych do nowego formatu — wykonaj kopię zapasową bazy danych (pełną kopię zapasową StartOS) przed aktualizacją, jeśli jeszcze tego nie zrobiono.** Dodaje nowy potok wczytywania okładek, naturalne sortowanie, ulubione playlisty oraz znacznie szybszy import playlist w dużych bibliotekach. Naprawia też kilka problemów bezpieczeństwa: wstrzykiwanie SQL, IDOR w obsłudze własności udostępnień, obejście SSRF w klientach HTTP/WebSocket wtyczek oraz obejście limitu prób logowania. Upstream dodaje też eksperymentalne API Jellyfin Music, ale nie jest ono jeszcze dostępne w tym pakiecie — kilka klientów nie może się z nim zsynchronizować w tej wersji, a poprawka nie znajduje się jeszcze w otagowanej wersji Navidrome.`,
    fr_FR: `Met à jour Navidrome vers la 0.64.0. **Cette version réencode tous les identifiants de la base de données dans un nouveau format — sauvegardez votre base de données (une sauvegarde StartOS complète) avant la mise à jour si ce n'est pas déjà fait.** Ajoute un nouveau pipeline de chargement des pochettes, un tri naturel, les favoris de playlists, et un import de playlists bien plus rapide sur les grandes bibliothèques. Corrige aussi plusieurs failles de sécurité : injection SQL, IDOR sur la propriété des partages, contournement SSRF dans les clients HTTP/WebSocket des plugins, et contournement de la limite de tentatives de connexion. En amont, une API Jellyfin Music expérimentale est aussi ajoutée, mais elle n'est pas encore disponible dans ce paquet — plusieurs clients ne peuvent pas s'y synchroniser dans cette version, et le correctif n'est pas encore dans une version taguée de Navidrome.`,
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
